    name: Run Python tests

    on:
      push:
        branches:
          - main
          - dev
      pull_request:
        branches:
          - main
          - dev

    jobs:
      build:
        runs-on: ubuntu-latest # Use the latest Ubuntu runner

        steps:
          - uses: actions/checkout@v4 # Checkout your repository code
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.x' # Specify your Python version
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt # Install dependencies from requirements.txt
              pip install .
          - name: Run tests with pytest
            run: pytest # Execute your tests using pytest